app/routes/artist.py
from app.extensions import db, format_datetime
from flask import Flask, render_template, request, Response, flash, redirect, url_for, jsonify, Blueprint

from app.models import Artist, Show
from app.forms import *


artist = Blueprint('artist', __name__)









#  Artists
#  ----------------------------------------------------------------
@artist.route('/artists')
def artists():
  # TODO: replace with real data returned from querying the database


  data = Artist.query.all()
  return render_template('pages/artists.html', artists=data)

@artist.route('/artists/search', methods=['POST'])
def search_artists():
  # TODO: implement search on artists with partial string search. Ensure it is case-insensitive.
  # seach for "A" should return "Guns N Petals", "Matt Quevado", and "The Wild Sax Band".
  # search for "band" should return "The Wild Sax Band".

  search = request.form.get('search_term', '')

  result = Artist.query.filter(Artist.name.ilike("%" + search + "%")).all()
  
  response = {
        "count": len(result),
        "data": result
    }

  return render_template('pages/search_artists.html', results=response, search_term=request.form.get('search_term', ''))

@artist.route('/artists/<int:artist_id>')
def show_artist(artist_id):
  # shows the venue page with the given venue_id
  # TODO: replace with real venue data from the venues table, using venue_id

  

  artist = Artist.query.filter_by(id=artist_id).one()

  shows = Show.query.filter_by(artist_id=artist_id).all()

  past_shows = []
  upcoming_shows = []

  current_time = datetime.now()

  for show in shows:

    data = {
          "artist_id": show.venue_id,
          "artist_name": show.venue.name,
           "artist_image_link": show.venue.image_link,
           "start_time": format_datetime(str(show.start_time))
        }
    if show.start_time > current_time:
      upcoming_shows.append(data)
    else:
      past_shows.append(data)


  data={
    "id": artist.id,
    "name": artist.name,
    "genres": artist.genres,
    "city": artist.city,
    "state": artist.state,
    "phone": artist.phone,
    "website": artist.website,
    "facebook_link": artist.facebook_link,
    "seeking_talent": artist.seeking_venue,
    "seeking_description":artist.description,
    "image_link": artist.image_link,
    "past_shows": past_shows,
    "upcoming_shows": upcoming_shows,
    "past_shows_count": len(past_shows),
    "upcoming_shows_count": len(upcoming_shows)
  }
  
  
  return render_template('pages/show_artist.html', artist=data)




#  Update
#  ----------------------------------------------------------------
@artist.route('/artists/<int:artist_id>/edit', methods=['GET'])
def edit_artist(artist_id):
  form = ArtistForm()
  artist = Artist.query.get(artist_id)
  # TODO: populate form with fields from artist with ID <artist_id>
  return render_template('forms/edit_artist.html', form=form, artist=artist)

@artist.route('/artists/<int:artist_id>/edit', methods=['POST'])
def edit_artist_submission(artist_id):
  # TODO: take values from the form submitted, and update existing
  # artist record with ID <artist_id> using the new attributes
  form = ArtistForm(request.form)
  result = Artist.query.filter_by(id=artist_id).one()

  try:
    

    result.name = form.name.data
   
    result.city = form.city.data
    result.state = form.state.data
    result.phone = form.phone.data
    result.genres = form.genres.data
    result.facebook_link = form.facebook_link.data
    result.website = form.website.data
    result.image_link = form.image_link.data
    result.seeking_talent = form.seeking_venue.data
    result.description = form.description.data
    db.session.add(result)
    db.session.commit()
    flash('Artist ' + form.name.data + ' was successfully Edited!')

  except:
    db.session.rollback()
    flash('An error occurred. Artist ' + form.name.data + ' could not be Edited.')
    

  finally:
    db.session.close()
    

  return redirect(url_for('artist.show_artist', artist_id=artist_id))




#  Create Artist
#  ----------------------------------------------------------------

@artist.route('/artists/create', methods=['GET'])
def create_artist_form():
  form = ArtistForm()
  return render_template('forms/new_artist.html', form=form)


@artist.route('/artists/create', methods=['POST'])
def create_artist_submission():

  form = ArtistForm(request.form)

  try:
    new_artist = Artist(
      name=form.name.data,
      city=form.city.data,
      state=form.state.data,
      phone=form.phone.data,
      genres=form.genres.data,
      
      
      image_link=form.image_link.data,
      website = form.website.data,
      facebook_link=form.facebook_link.data,
      
      description = form.description.data,
      seeking_venue = form.seeking_venue.data)
    db.session.add(new_artist)
    db.session.commit()
    flash('Artist ' + form.name.data + ' was successfully listed!')

  except:
    db.session.rollback()
    flash('An error occurred. Artist ' + form.name.data + ' could not be listed.')

  finally:
    db.session.close()


 

  

  return render_template('pages/home.html')

app/routes/show.py
from app.extensions import db
from flask import Flask, render_template, request, Response, flash, redirect, url_for, jsonify, Blueprint

from app.models import Show, Venue, Artist
from app.forms import *


show = Blueprint('show', __name__)




#  Shows
#  ----------------------------------------------------------------



@show.route('/shows')
def shows():

  shows = Show.query.all()


  data = []


  for show in shows:
        venue = Venue.query.get(show.venue_id)
        artist = Artist.query.get(show.artist_id)
        data.extend([{
            "venue_id": venue.id,
            "venue_name": venue.name,
            "artist_id": artist.id,
            "artist_name": artist.name,
            "artist_image_link": artist.image_link,
            "start_time": show.start_time.strftime("%m/%d/%Y, %H:%M")
        }])
  
  return render_template('pages/shows.html', shows=data)



@show.route('/shows/create')
def create_shows():
  # renders form. do not touch.
  form = ShowForm()
  return render_template('forms/new_show.html', form=form)


@show.route('/shows/create', methods=['POST'])
def create_show_submission():

  form = ShowForm()

  try:
    show = Show()
    show.artist_id = form.artist_id.data
    show.venue_id = form.venue_id.data
    show.start_time = form.start_time.data
    db.session.add(show)
    db.session.commit()

    # on successful db insert, flash success
    flash('Show was successfully listed!')
  except:
    db.session.rollback()
    flash('An error occurred. Show could not be listed.')

  finally:
    db.session.close()

  # see: http://flask.pocoo.org/docs/1.0/patterns/flashing/
  return render_template('pages/home.html')

app/routes/venue.py
from app.extensions import db, format_datetime
from flask import Flask, render_template, request, Response, flash, redirect, url_for, jsonify, Blueprint

from app.models import Venue, Show
from app.forms import *




venue = Blueprint('venue', __name__)













@venue.route('/venues')
def venues():
  # TODO: replace with real venues data.
  #       num_shows should be aggregated based on number of upcoming shows per venue.
  
  result=[]

  venues = db.session.query(Venue.city, Venue.state).distinct(Venue.city, Venue.state)

  for venue in venues:
      venues_in_city = db.session.query(Venue.id, Venue.name).filter(Venue.city == venue[0]).filter(Venue.state == venue[1])
      result.append({
        "city": venue[0],
        "state": venue[1],
        "venues": venues_in_city
      })
  
  
  return render_template('pages/venues.html', areas=result)


@venue.route('/venues/search', methods=['POST'])
def search_venues():
  # TODO: implement search on artists with partial string search. Ensure it is case-insensitive.
  # seach for Hop should return "The Musical Hop".
  # search for "Music" should return "The Musical Hop" and "Park Square Live Music & Coffee"
  search = request.form.get('search_term', '')

  result = Venue.query.filter(Venue.name.ilike("%" + search + "%")).all()
  
  response = {
        "count": len(result),
        "data": result
    }

  return render_template('pages/search_venues.html', results=response, search_term=request.form.get('search_term', ''))




@venue.route('/venues/<int:venue_id>')
def show_venue(venue_id):
  # shows the venue page with the given venue_id
  # TODO: replace with real venue data from the venues table, using venue_id

  venue = Venue.query.filter_by(id=venue_id).one()

  shows = Show.query.filter_by(venue_id=venue_id).all()

  past_shows = []
  upcoming_shows = []

  current_time = datetime.now()

  for show in shows:

    data = {
          "artist_id": show.artist_id,
          "artist_name": show.artist.name,
           "artist_image_link": show.artist.image_link,
           "start_time": format_datetime(str(show.start_time))
        }
    if show.start_time > current_time:
      upcoming_shows.append(data)
    else:
      past_shows.append(data)

  data={
    "id": venue.id,
    "name": venue.name,
    "genres": venue.genres,
    "address": venue.address,
    "city": venue.city,
    "state": venue.state,
    "phone": venue.phone,
    "website": venue.website,
    "facebook_link": venue.facebook_link,
    "seeking_talent": venue.seeking_talent,
    "seeking_description":venue.description,
    "image_link": venue.image_link,
    "past_shows": past_shows,
    "upcoming_shows": upcoming_shows,
    "past_shows_count": len(past_shows),
    "upcoming_shows_count": len(upcoming_shows)
  }
  
  return render_template('pages/show_venue.html', venue=data)


#  Create Venue
#  ----------------------------------------------------------------

@venue.route('/venues/create', methods=['GET'])
def create_venue_form():
  form = VenueForm()
  return render_template('forms/new_venue.html', form=form)


@venue.route('/venues/create', methods=['POST'])
def create_venue_submission():
  # TODO: insert form data as a new Venue record in the db, instead
  # TODO: modify data to be the data object returned from db insertion
  form = VenueForm(request.form)

  try:
    new_venue = Venue(
      name=form.name.data,
      city=form.city.data,
      state=form.state.data,
      address=form.address.data,
      genres = form.genres.data,
      phone=form.phone.data,
      image_link=form.image_link.data,
      seeking_talent = form.seeking_talent.data,
      
      facebook_link=form.facebook_link.data,
      description = form.description.data,
      website = form.website.data
      
      
    )

    

    db.session.add(new_venue)
    db.session.commit()

    # on successful db insert, flash success
    flash('Venue ' + request.form['name'] + ' was successfully listed!')
  except:
    db.session.rollback()

    flash('An error occurred. Venue ' + data.name + ' could not be listed.')
  finally:
    db.session.close()

  
  # TODO: on unsuccessful db insert, flash an error instead.
  # e.g., flash('An error occurred. Venue ' + data.name + ' could not be listed.')
  # see: http://flask.pocoo.org/docs/1.0/patterns/flashing/
  return render_template('pages/home.html')




@venue.route('/venues/<venue_id>', methods=['DELETE'])
def delete_venue(venue_id):
  # TODO: Complete this endpoint for taking a venue_id, and using
  # SQLAlchemy ORM to delete a record. Handle cases where the session commit could fail.

  # BONUS CHALLENGE: Implement a button to delete a Venue on a Venue Page, have it so that
  # clicking that button delete it from the db then redirect the user to the homepage

  try:
    venue = Venue.query.filter_by(id=venue_id).first_or_404()

    db.session.delete(venue)
    
    db.session.commit()
    
    flash('Venue has been removed!')


    return render_template('pages/home.html')

  except:
    db.session.rollback()
    flash('Venue could not be removed!')

  finally:
    db.session.close()

    
  return None




#  Update
#  ----------------------------------------------------------------

@venue.route('/venues/<int:venue_id>/edit', methods=['GET'])
def edit_venue(venue_id):
  form = VenueForm(request.form)

  result = Venue.query.filter_by(id=venue_id).one()


  form.state.process_data(result.state)
  form.genres.process_data(result.genres)
  
  # TODO: populate form with values from venue with ID <venue_id>
  return render_template('forms/edit_venue.html', form=form, venue=result)



@venue.route('/venues/<int:venue_id>/edit', methods=['POST'])
def edit_venue_submission(venue_id):
  # TODO: take values from the form submitted, and update existing
  form = VenueForm(request.form)
  result = Venue.query.filter_by(id=venue_id).one()

  try:
     result.name = form.name.data
     result.genres = form.genres.data
     result.address = form.address.data
     result.city = form.city.data
     result.state = form.state.data
     result.phone = form.phone.data
     result.facebook_link = form.facebook_link.data
     result.website = form.website.data
     result.image_link = form.image_link.data
     result.seeking_talent = form.seeking_talent.data
     result.description = form.description.data
     db.session.add(result)
     db.session.commit()

     flash('Venue ' + form.name.data + ' was successfully Edited!')

  except:
    db.session.rollback()
    return('An error occurred')
    
    flash('An error occurred. Venue ' + form.name.data + ' could not be Edited.')

  finally:
    db.session.close()
  
  # venue record with ID <venue_id> using the new attributes
  return redirect(url_for('venue.show_venue', venue_id=venue_id))

app/templates/pages/artists.html
{% extends 'layouts/main.html' %}
{% block title %}Fyyur | Artists{% endblock %}
{% block content %}
<ul class="items">
	{% for artist in artists %}
	<li>
		<a href="/artists/{{ artist.id }}">
			<i class="fas fa-users"></i>
			<div class="item">
				<h5>{{ artist.name }}</h5>
			</div>
		</a>
	</li>
	{% endfor %}
</ul>
{% endblock %}

app/templates/pages/home.html
{% extends 'layouts/main.html' %}
{% block title %}Fyyur{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-6">
		<h1>Fyyur 🔥</h1>
		<p class="lead">Where musical artists meet musical venues.</p>
		<h3>
			<a href="/venues"><button class="btn btn-primary btn-lg">Find a venue</button></a>
			<a href="/venues/create"><button class="btn btn-default btn-lg">Post a venue</button></a>
		</h3>
		<h3>
			<a href="/artists"><button class="btn btn-primary btn-lg">Find an artist</button></a>
			<a href="/artists/create"><button class="btn btn-default btn-lg">Post an artist</button></a>
		</h3>
		<p class="lead">Publicize about your show for free.</p>
		<h3>
			<a href="/shows/create"><button class="btn btn-default btn-lg">Post a show</button></a>
		</h3>
	</div>
	<div class="col-sm-6 hidden-sm hidden-xs">
		<img id="front-splash" src="{{ url_for('static',filename='img/front-splash.jpg') }}" alt="Front Photo of Musical Band" />
	</div>
</div>
{% endblock %}

app/templates/pages/search_artists.html
{% extends 'layouts/main.html' %}
{% block title %}Fyyur | Artists Search{% endblock %}
{% block content %}
<h3>Number of search results for "{{ search_term }}": {{ results.count }}</h3>
<ul class="items">
	{% for artist in results.data %}
	<li>
		<a href="/artists/{{ artist.id }}">
			<i class="fas fa-users"></i>
			<div class="item">
				<h5>{{ artist.name }}</h5>
			</div>
		</a>
	</li>
	{% endfor %}
</ul>
{% endblock %}

app/templates/pages/search_venues.html
{% extends 'layouts/main.html' %}
{% block title %}Fyyur | Venues Search{% endblock %}
{% block content %}
<h3>Number of search results for "{{ search_term }}": {{ results.count }}</h3>
<ul class="items">
	{% for venue in results.data %}
	<li>
		<a href="/venues/{{ venue.id }}">
			<i class="fas fa-music"></i>
			<div class="item">
				<h5>{{ venue.name }}</h5>
			</div>
		</a>
	</li>
	{% endfor %}
</ul>
{% endblock %}

app/templates/pages/show.html
{% extends 'layouts/main.html' %}
{% block title %}Show Search{% endblock %}
{% block content %}

    <div class="page-header">
        <h1>Fyyur Search!</h1>
    </div>
    <p class="lead"> Show Search </p>

    <ul class="nav nav-pills">
        <li class="active"><a>Shows</a></li>
    </ul>

{#    Todo implement show search frontend #}

{% endblock %}

app/templates/pages/show_artist.html
{% extends 'layouts/main.html' %}
{% block title %}{{ artist.name }} | Artist{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-6">
		<h1 class="monospace">
			{{ artist.name }}
		</h1>
		<p class="subtitle">
			ID: {{ artist.id }}
		</p>
		<div class="genres">
			{% for genre in artist.genres %}
			<span class="genre">{{ genre }}</span>
			{% endfor %}
		</div>
		<p>
			<i class="fas fa-globe-americas"></i> {{ artist.city }}, {{ artist.state }}
		</p>
		<p>
			<i class="fas fa-phone-alt"></i> {% if artist.phone %}{{ artist.phone }}{% else %}No Phone{% endif %}
        </p>
        <p>
			<i class="fas fa-link"></i> {% if artist.website %}<a href="{{ artist.website }}" target="_blank">{{ artist.website }}</a>{% else %}No Website{% endif %}
		</p>
		<p>
			<i class="fab fa-facebook-f"></i> {% if artist.facebook_link %}<a href="{{ artist.facebook_link }}" target="_blank">{{ artist.facebook_link }}</a>{% else %}No Facebook Link{% endif %}
        </p>
		{% if artist.seeking_venue %}
		<div class="seeking">
			<p class="lead">Currently seeking performance venues</p>
			<div class="description">
				<i class="fas fa-quote-left"></i> {{ artist.description }} <i class="fas fa-quote-right"></i>
			</div>
		</div>
		{% else %}	
		<p class="not-seeking">
			<i class="fas fa-moon"></i> Not currently seeking performance venues
		</p>
		{% endif %}
	</div>
	<div class="col-sm-6">
		<img src="{{ artist.image_link }}" alt="Venue Image" />
	</div>
</div>
<section>
	<h2 class="monospace">{{ artist.upcoming_shows_count }} Upcoming {% if artist.upcoming_shows_count == 1 %}Show{% else %}Shows{% endif %}</h2>
	<div class="row">
		{%for show in artist.upcoming_shows %}
		<div class="col-sm-4">
			<div class="tile tile-show">
				<img src="{{ show.venue_image_link }}" alt="Show Venue Image" />
				<h5><a href="/venues/{{ show.venue_id }}">{{ show.venue_name }}</a></h5>
				<h6>{{ show.start_time|datetime('full') }}</h6>
			</div>
		</div>
		{% endfor %}
	</div>
</section>
<section>
	<h2 class="monospace">{{ artist.past_shows_count }} Past {% if artist.past_shows_count == 1 %}Show{% else %}Shows{% endif %}</h2>
	<div class="row">
		{%for show in artist.past_shows %}
		<div class="col-sm-4">
			<div class="tile tile-show">
				<img src="{{ show.venue_image_link }}" alt="Show Venue Image" />
				<h5><a href="/venues/{{ show.venue_id }}">{{ show.venue_name }}</a></h5>
				<h6>{{ show.start_time|datetime('full') }}</h6>
			</div>
		</div>
		{% endfor %}
	</div>
</section>


<div class="row">
	<div class="col-sm-3">
	  <a href="{{ url_for('artist.edit_artist', artist_id=artist.id) }}"
		 class="btn btn-primary btn-lg btn-block">Edit Artist</a>
	</div>
	
  </div>

{% endblock %}

app/templates/pages/show_venue.html
{% extends 'layouts/main.html' %}
{% block title %}Venue Search{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-6">
		<h1 class="monospace">
			{{ venue.name }}
		</h1>
		<p class="subtitle">
			ID: {{ venue.id }}
		</p>
		<div class="genres">
			{% for genre in venue.genres %}
			<span class="genre">{{ genre  }}</span>
			{% endfor %}
		</div>
		<p>
			<i class="fas fa-globe-americas"></i> {{ venue.city }}, {{ venue.state }}
		</p>
		<p>
			<i class="fas fa-map-marker"></i> {% if venue.address %}{{ venue.address }}{% else %}No Address{% endif %}
		</p>
		<p>
			<i class="fas fa-phone-alt"></i> {% if venue.phone %}{{ venue.phone }}{% else %}No Phone{% endif %}
		</p>
		<p>
			<i class="fas fa-link"></i> {% if venue.website %}<a href="{{ venue.website }}" target="_blank">{{ venue.website }}</a>{% else %}No Website{% endif %}
		</p>
		<p>
			<i class="fab fa-facebook-f"></i> {% if venue.facebook_link %}<a href="{{ venue.facebook_link }}" target="_blank">{{ venue.facebook_link }}</a>{% else %}No Facebook Link{% endif %}
		</p>
		{% if venue.seeking_talent %}
		<div class="seeking">
			<p class="lead">Currently seeking talent</p>
			<div class="description">
				<i class="fas fa-quote-left"></i> {{ venue.description }} <i class="fas fa-quote-right"></i>
			</div>
		</div>
		{% else %}	
		<p class="not-seeking">
			<i class="fas fa-moon"></i> Not currently seeking talent
		</p>
		{% endif %}
	</div>
	<div class="col-sm-6">
		<img src="{{ venue.image_link }}" alt="Venue Image" />
	</div>
</div>
<section>
	<h2 class="monospace">{{ venue.upcoming_shows_count }} Upcoming {% if venue.upcoming_shows_count == 1 %}Show{% else %}Shows{% endif %}</h2>
	<div class="row">
		{%for show in venue.upcoming_shows %}
		<div class="col-sm-4">
			<div class="tile tile-show">
				<img src="{{ show.artist_image_link }}" alt="Show Artist Image" />
				<h5><a href="/artists/{{ show.artist_id }}">{{ show.artist_name }}</a></h5>
				<h6>{{ show.start_time|datetime('full') }}</h6>
			</div>
		</div>
		{% endfor %}
	</div>
</section>
<section>
	<h2 class="monospace">{{ venue.past_shows_count }} Past {% if venue.past_shows_count == 1 %}Show{% else %}Shows{% endif %}</h2>
	<div class="row">
		{%for show in venue.past_shows %}
		<div class="col-sm-4">
			<div class="tile tile-show">
				<img src="{{ show.artist_image_link }}" alt="Show Artist Image" />
				<h5><a href="/artists/{{ show.artist_id }}">{{ show.artist_name }}</a></h5>
				<h6>{{ show.start_time|datetime('full') }}</h6>
			</div>
		</div>
		{% endfor %}
	</div>
</section>


<div class="row">
	<div class="col-sm-3">
	  <a href="{{ url_for('venue.edit_venue', venue_id=venue.id) }}"
		 class="btn btn-primary btn-lg btn-block">Edit Venue</a>
	</div>

	<div class="col-sm-3">
		<button id="delete-venue" data-id="{{ venue.id }}" class="btn btn-primary btn-lg btn-block">Delete Venue</button>
	  </div>

	

  </div>



  <script>
	const deleteBtn = document.getElementById('delete-venue')
	deleteBtn.onclick = function(e) {
	  const venueId = e.target.dataset['id']
	  fetch('/venues/' + venueId, {
		method: 'DELETE'
	  })
	  
	  .then(function() {
	        window.location.href = '/venues';
	})
	.catch(function(e) {
		console.log('error', e)
	})
	}
  </script>



{% endblock %}

app/templates/pages/shows.html
{% extends 'layouts/main.html' %}
{% block title %}Fyyur | Shows{% endblock %}
{% block content %}
<div class="row shows">
    {%for show in shows %}
    <div class="col-sm-4">
        <div class="tile tile-show">
            <img src="{{ show.artist_image_link }}" alt="Artist Image" />
            <h4>{{ show.start_time }}</h4>
            <h5><a href="/artists/{{ show.artist_id }}">{{ show.artist_name }}</a></h5>
            <p>playing at</p>
            <h5><a href="/venues/{{ show.venue_id }}">{{ show.venue_name }}</a></h5>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/pages/venues.html
{% extends 'layouts/main.html' %}
{% block title %}Fyyur | Venues{% endblock %}
{% block content %}


{% for area in areas %}
<h3>{{ area.city }}, {{ area.state }}</h3>
<ul class="items">
  {% for venue in area.venues %}
  <li>
    <a href="/venues/{{ venue.id }}">
      <i class="fas fa-music"></i>
      <div class="item">
        <h5>{{ venue.name }}</h5>
      </div>
    </a>
  </li>
  {% endfor %}
</ul>
{% endfor %}



</script>

{% endblock %}